wemadefree/WeBook

- webook/templates/account/email.html
- webook/templates/account/password_reset.html
- webook/templates/users/user_detail.html
- webook/templates/users/user_form.html
- webook/templates/users/users_base.html
**Summary**
This PR introduces a basic shell of a "_My Profile/My User_" page, with a good layout structure that can be expanded and built upon further as our user/profile model grows.
> Set up a basic shell/structure of a "My Profile" section

- docs/Makefile
- docs/conf.py
- docs/config.rst
- docs/config.settings.rst
- docs/index.rst
- docs/make.bat
- docs/manage.rst
- docs/modules.rst
- docs/webook.arrangement.migrations.rst
- docs/webook.arrangement.rst
- docs/webook.contrib.rst
- docs/webook.contrib.sites.migrations.rst
- docs/webook.contrib.sites.rst
- docs/webook.rst
- docs/webook.users.migrations.rst
- docs/webook.users.rst
- docs/webook.users.tests.rst
- docs/webook.utils.rst
- requirements/base.txt
**Summary**
This PR introduces Sphinx as a dependency, and sets up Sphinx. 
**Concrete**
- Added Sphinx as a requirement to base.txt
- Set up a new folder in root of project, called "docs"
- Ran sphinx-quickstart inside of docs folder
- Configured docs/conf.py to find config/settings/local.py package, and use this as settings base. Not sure if we would want production.py instead.
- Ran sphinx-apidoc to automatically generate documentation
- Ran make html to generate html documentation files
> Install Sphinx

- webook/templates/base.html
This PR introduces a sidebar to base.html. This sidebar has been implemented with some placeholder links to different sections of the application we know will be implemented with time. Additionally it has also been written with the presumption that it will only be shown when a user is logged in - thus one should not need to do any edge-case handling of logged-in/logged-out.
Additionally this also introduces FontAwesome as a dependency. It seems better to use this than LineAwesome.
> Implement sidebar

- webook/arrangement/forms/__init__.py
- webook/arrangement/urls.py
- webook/arrangement/views/__init__.py
This PR introduces a sort of structural standard for how we are to implement views and forms for the Arrangement app in the future. The core achievements of this PR is allowing for views to be split into files, so one can for instance have a location_views.py file. This means that instead of having all views for all models in one file (very messy) we can now split them out into model-specific view files. The same goes for forms.
These are all imported into the same urls.py file, where the views are categorized by comments instead.
_Is identical to #52, managed to mangle that branch a little, so reupped it correctly here_
> Create view structure

- README.md
This PR introduces an update to README.md. Documentation around the ENV variables has been added.
> Update readme with info about ENV variables

- package-lock.json
- package.json
This PR installs (adds as dependency?) Vis timeline to WeBook, via NPM.
> Install vis timeline

- webook/arrangement/models.py
- webook/arrangement/views/__init__.py
- webook/arrangement/views/arrangement_views.py
- webook/templates/arrangement/arrangement/arrangement_detail.html
- webook/templates/arrangement/arrangement/arrangement_form.html
- webook/templates/arrangement/delete_view.html
- webook/templates/arrangement/list_view.html
- webook/templates/arrangement/meta_base.html
- webook/utils/crudl/view_mixins.py
- webook/utils/meta/meta_model_mixins.py
- webook/utils/meta/meta_types.py
- webook/utils/meta/meta_view_mixins.py
This PR sets up the basic CRUDL views/templates/functionality for arrangements. There's a lot to come here once the planner utility/wizard is developed.
Depends on #82
> Setup arrangement section

- webook/templates/base.html
This PR concerns primarily the base template. It adds handling of the header of the page, using the metadata infrastructure and crumbinator. 
Also lifted the sidemenu from the preview branch so that won't have to be done over again.
> Rewrite base template to use meta utils

- webook/arrangement/forms/add_planners_form.py
- webook/arrangement/forms/remove_planners_form.py
- webook/arrangement/urls/planner_urls.py
- webook/arrangement/views/__init__.py
- webook/arrangement/views/planner_views.py
- webook/static/modules/planner/arrangementInspector.js
- webook/static/modules/planner/plannerCalendar.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/addPlannerDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/arrangementInfoDialog.html
- webook/templates/arrangement/planner/planner_calendar.html
Fixes and polishes, as well as updating info dialog/inspector to be able to add/remove planners.
> Update arrangement info dialog

- webook/templates/base.html
> Implement Zen Mode

- webook/arrangement/models.py
Modelling business hours module that can be plugged into rooms and people sections respectively as well organizations
> Nasj-112/modeling business hours

- webook/static/modules/planner/arrangementCreator.js
- webook/static/modules/planner/arrangementInspector.js
- webook/static/modules/planner/dialog_manager/dialogManager.js
Touch up and make flows of dialogs more sensible. Close form dialogs when they have been submitted.
Make sure onUpdatedCallbacks are called by DialogManager.
> Close when form dialog is submitted

- webook/arrangement/models.py
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createArrangementDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createSerieDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/dialog_create_event_arrangement.html
- webook/templates/arrangement/planner/planner_calendar.html
Add validation to the arrangement planning/creation dialogs.
> Arrangement creator dialog validation

- webook/arrangement/views/planner_views.py
- webook/static/modules/planner/commonLib.js
- webook/static/modules/planner/plannerCalendar.js
> Constrain calendar query to date span being viewed

- config/settings/base.py
- webook/static/modules/planner/plannerCalendar.js
- webook/templates/arrangement/location/location_detail.html
- webook/templates/arrangement/planner/planner_calendar.html
- webook/templates/users/user_detail.html
License keys were not being "fed" into most calendars. This fixes that.
> Fix fc license key feeding

- webook/arrangement/views/arrangement_views.py
- webook/arrangement/views/generic_views/json_form_view.py
- webook/arrangement/views/note_views.py
- webook/arrangement/views/planner_views.py
- webook/arrangement/views/requisition_views.py
Create custom JsonFormView.
Use this on forms where we dont care about the response / just want an OK / fetch/ajax.
> Fix deleteviews and blackhole views

- webook/arrangement/views/planner_views.py
- webook/static/modules/planner/arrangementCreator.js
Bug fix that fixes an issue where on serie creation the english title of the events of the serie would not be set with the value defined in the serie creation.
> Fix inconsistencies with event en title on inspect event

- webook/arrangement/exceptions.py
- webook/arrangement/views/calendar_views.py
- webook/utils/serie_calculator.py
1. Refactored docstring on EventSourceViewMixin, using Google Standards, which seemed to recommended. 
2. Added docstring to UserHasNoPersonException (as well as set up a Wiki page for exceptions, and detailed it there)
> Changes in relation to PR #219

- webook/arrangement/managers.py
- webook/arrangement/models.py
- webook/arrangement/views/calendar_views.py
Create a custom manager for the Event model, so that we can add the "get all events in a given range" logic in one central place, instead of repeating the implementation.
Also refactored EventManager.get methods logic for getting events in a time range to use the new method on the manager.
> Create custom event manager

- webook/static/modules/planner/commonLib.js
- webook/static/modules/planner/plannerCalendar.js
- webook/static/modules/planner/plannerCalendarFilter.js
- webook/templates/arrangement/planner/planner_calendar.html
Implement a switch to filter the calendar, so that if the switch is checked, the calendar will only display events that do not have any rooms assigned.
> Implement filter for showing/hiding events based on if they have rooms assigned or not

- webook/static/css/project.css
- webook/static/modules/planner/arrangementCreator.js
- webook/static/modules/planner/arrangementInspector.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createSerieDialog.html
Redesign the create serie dialog.
> Redesign create serie dialog

- webook/arrangement/forms/event_forms.py
- webook/arrangement/forms/exclusivity_analysis/serie_manifest_form.py
- webook/arrangement/views/event_views.py
- webook/static/modules/planner/arrangementInspector.js
- webook/static/modules/planner/form_populating_routines.js
- webook/static/modules/planner/querystore.js
- webook/static/modules/planner/serieConvert.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/inspectEventDialog.html
Fixes bugs on save serie, save event, and update event, where relationships would not be saved correctly. Not sure why this happens, and I will investigate in further detail, but this is a band-aid for the time being until I can figure out what has happened. This worked correctly in my feature branch so there is something weird going on.
> Fix saving bugs on relationships

- webook/static/modules/planner/arrangementInspector.js
- webook/static/modules/planner/querystore.js
Small improvements and formatting standardizations on arrangement inspector
> Cleanups on arrangement inspector

- webook/static/modules/planner/arrangementCreator.js
Minor code cleanup and formatting fixes on arrangementCreator
> Cleanup and formatting on arrangementCreator

- webook/static/modules/planner/arrangementCreator.js
- webook/static/modules/planner/arrangementInspector.js
- webook/static/modules/planner/eventInspector.js
Close the order person dialog after selecting people and clicking save/select button.
> Close order person dialog after saving

- webook/static/modules/planner/plannerCalendarFilter.js
> Close filter dialog after setting filter

- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/orderPersonDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/orderRoomDialog.html
Add DataTables to the person selector dialog, as to make it searchable.
> Make person selector dialog searchable

- webook/arrangement/views/planner_views.py
- webook/static/modules/planner/plannerCalendar.js
Some minor adjustments and improvements to the event popover.
For now redesigned the popover to get some more information, and have it presented in a more aesthetically pleasing way. Additionally also added badges that indicate the hovered events state in terms of serie relations. One can now see through the popover if the event is a part of a serie, has been broken out of a serie, or is a single standalone activity. 
Additionally also added a stamp to the bottom showing when the arrangement was created.
> Improve event popover

- webook/arrangement/forms/post_note_form.py
- webook/arrangement/urls/planner_urls.py
- webook/arrangement/views/__init__.py
- webook/arrangement/views/note_views.py
- webook/arrangement/views/planner_views.py
- webook/static/modules/planner/arrangementInspector.js
- webook/static/modules/planner/dialog_manager/dialogManager.js
- webook/static/modules/planner/eventInspector.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/arrangementInfoDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createSerieDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/inspectEventDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/newNoteDialog.html
- webook/templates/base.html
This PR introduces note functionality to events (inspect event dialog).
Additionally I have redesigned the newNoteDialog, and enabled editing as well as deleting of a note. Should be a tad more usable now. I also needed to refactor the NewNoteDialogView so as to be able to seamlessly work with different models - I am not sure if this is the best long-term approach (just if/elses on the eventType string name), but for now it works.
> Implement notes on event

- webook/static/modules/planner/arrangementCreator.js
Fix a bug that caused the new simple activity dialog to not work as intended.
> Fix context.events undefined bug messing up newActivity dialog

- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createSerieDialog.html
Fix a bug where room chips selected could not be removed, and would not be heeded on save of the serie.
> Fix room chips not removable bug

- webook/arrangement/forms/person_forms.py
- webook/arrangement/urls/person_urls.py
- webook/arrangement/views/__init__.py
- webook/arrangement/views/person_views.py
- webook/templates/arrangement/person/associate_person_with_user.html
- webook/templates/arrangement/person/person_detail.html
Implement functionality / page for associating a person with user(s).
> Implement functionality for associating people with users

- webook/arrangement/views/analysis_views.py
- webook/arrangement/views/arrangement_views.py
- webook/arrangement/views/arrangementtype_views.py
- webook/arrangement/views/audience_views.py
- webook/arrangement/views/calendar_views.py
- webook/arrangement/views/event_views.py
- webook/arrangement/views/location_views.py
- webook/arrangement/views/note_views.py
- webook/arrangement/views/organization_views.py
- webook/arrangement/views/organizationtype_views.py
- webook/arrangement/views/person_views.py
- webook/arrangement/views/planner_views.py
- webook/arrangement/views/requisition_views.py
- webook/arrangement/views/room_preset_views.py
- webook/arrangement/views/room_views.py
- webook/arrangement/views/servicetype_views.py
- webook/arrangement/views/status_type_views.py
- webook/authorization_mixins.py
- webook/static/modules/planner/plannerCalendar.js
- webook/templates/403.html
- webook/templates/arrangement/planner/planner_calendar.html
- webook/templates/base.html
- webook/users/adapters.py
Implement two new roles, read only and planner .You must be planner, or super user, to use the higher level planning functions. Added a custom mixin for authorization (pretty much saying, you need to be of x role to use this view).
All new users created during SSO signup will be added to the readonly group.
> Read only role

- webook/users/adapters.py
Change the SSO link to be based on the social provider ID
> Change sso link to be social provider id

- config/settings/production.py
- webook/static/modules/planner/arrangementCreator.js
- webook/static/modules/planner/arrangementInspector.js
- webook/static/modules/planner/dialog_manager/dialogManager.js
- webook/static/modules/planner/eventInspector.js
Make it so that when a parent or root dialog is closed, its children are closed as well.
> Adjust arrangement dialog close behaviour

- webook/static/modules/planner/arrangementInspector.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/arrangementInfoDialog.html
Add scrollign to activities list/table on inspect arrangement dialog.
> Add scrolling to activities table

- webook/arrangement/forms/exclusivity_analysis/serie_manifest_form.py
- webook/arrangement/views/analysis_views.py
- webook/static/modules/planner/collisions_util.js
- webook/static/modules/planner/serieConvert.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createArrangementDialog.html
- webook/utils/collision_analysis.py
Fix a bug where on editing a serie it could be seen as colliding with itself. The past events should not be taken into account as they will be flushed/regenerated based on new edited serie.
> Fix bug where self collisions would be possible on serie edit

- webook/arrangement/views/planner_views.py
- webook/static/modules/planner/commonLib.js
- webook/static/modules/planner/plannerCalendar.js
- webook/templates/arrangement/planner/planner_calendar.html
Implement status type filter in plannercalendar in the same form as the other filters (jstree advanced filter components)
> implement status type filter in planner calendar

- webook/static/js/project.js
- webook/static/modules/planner/arrangementCreator.js
- webook/static/modules/planner/arrangementInspector.js
- webook/static/modules/planner/form_populating_routines.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createArrangementDialog.html
Fix up collision and break-out related functionality as a lot of it had "fallen out" due to newer functionalities and paradigm changes.
> Fix up collision functionality

- webook/arrangement/models.py
- webook/static/css/base.css
- webook/templates/common/dialog_list_view.html
- webook/templates/common/tree_list_view.html
- webook/templates/users/user_detail.html
- webook/users/views.py
Polish and fix up the generic tree_list_view and dialog_list_view templates. Improve design and usability, as well as solve some nuisances.
> Polish and fix up dialog tree_list_view and dialog_list_view

- webook/arrangement/models.py
- webook/templates/base.html
Automatically refresh notifications on interval (every second), using the JQuery shake effect  should state have changed since last load.
> Automatically refresh notifications every second, with effect

- webook/templates/base.html
Add the option to delete all notifications.
Additionally improve feedback and response handling on the other operations, mark all as seen, and delete single
> Add option delete all notifications

- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createArrangementDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createSerieDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/dialog_create_event_arrangement.html
Highlight obligatory fields in the planning process / flow dialogs (ux improvement.)
> Highlight obligatory fields

- webook/arrangement/signals.py
- webook/templates/arrangement/service/service_detail.html
This PR introduces logic for what should be done after a person is removed from the personell of a service (Service.resources).
When a person is removed now the person will also be removed from the service preconfigurations they are registered to, and the provisions they are added to.
> Handle person removed from service

- webook/arrangement/views/service_views.py
It is possible to see services in the services table/list that one is not responsible for. When attempting to work on these 403's would be returned, rightly so. This PR introduces filtering out of these services so that the user will not see services they are not responsible for.
> Show only the services one is responsible for in services list

- webook/templates/widgets/table_multi_select.html
> Refactor table_multi_select widget to use TableComponent

- webook/arrangement/forms/planner/planner_plan_serie_form.py
- webook/arrangement/views/planner_views.py
- webook/static/css/base.css
- webook/static/modules/planner/arrangementCreator.js
- webook/static/modules/planner/form_populating_routines.js
- webook/static/modules/planner/querystore.js
- webook/static/modules/planner/serieConvert.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createArrangementDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createSerieDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/dialog_create_event_arrangement.html
- webook/templates/arrangement/vue/arbitrator_select_component.html
- webook/templates/arrangement/vue/day_of_week_select_component.html
- webook/templates/arrangement/vue/month_select_component.html
- webook/templates/arrangement/vue/weekday_select_component.html
- webook/templates/base.html
- webook/utils/serie_calculator.py
Rewrite create serie dialog to use vue. Includes a lot of fixes and other stuff for activity and arrangement as well, as well as a shift in how form population is done.
> Rewrite create serie dialog to use vue

- webook/arrangement/urls/location_urls.py
- webook/arrangement/urls/room_preset_urls.py
- webook/arrangement/views/__init__.py
- webook/arrangement/views/location_views.py
- webook/arrangement/views/room_preset_views.py
- webook/static/css/base.css
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createArrangementDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createSerieDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/dialog_create_event_arrangement.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/orderRoomDialog.html
- webook/templates/arrangement/vue/dialog-component.html
- webook/templates/arrangement/vue/dialogs/order_room_dialog.html
- webook/templates/arrangement/vue/popover_component.html
- webook/templates/arrangement/vue/room_and_preset_selector_component.html
- webook/templates/arrangement/vue/room_presets_component.html
- webook/templates/arrangement/vue/table_component.html
This PR introduces a larger rewrite to accomodate a better and more user friendly UI / utility for ordering rooms and presets.
To achieve this a number of larger things had to be done (especially to be able to avoid repeating code between dialogs). The order room dialog had to be implemented in Vue, in relation to which I have written a vue dialog component that works similarly to the rest of the dialogs in the application (just a lot better, and is a lot more elegant to use)
> Rewrite order rooms functionality for improved UX and UI

- webook/arrangement/event_queries.py
- webook/arrangement/views/calendar_views.py
- webook/static/modules/planner/commonLib.js
- webook/static/modules/planner/plannerCalendar.js
- webook/templates/arrangement/planner/planner_calendar.html
- webook/templates/users/user_detail.html
Use the planner calendar functionality in the home calendar as well (allowing opening events and arrangements)
> Use planner calendar functionality in home calendar

- webook/arrangement/forms/event_forms.py
- webook/arrangement/urls/event_urls.py
- webook/arrangement/views/__init__.py
- webook/arrangement/views/event_views.py
- webook/templates/arrangement/planner/event-info-dialog.html
- webook/templates/arrangement/vue/rigging-form.html
- webook/users/views.py
Implement Vue rigging form component for event info dialog
> Make rigging form component

- package-lock.json
- package.json
- webook/arrangement/urls/room_urls.py
- webook/arrangement/views/__init__.py
- webook/arrangement/views/event_views.py
- webook/arrangement/views/room_views.py
- webook/static/css/base.css
- webook/templates/arrangement/planner/event-info-dialog.html
- webook/templates/arrangement/planner/planner_calendar_v2.html
- webook/templates/arrangement/vue/rooms-select.html
- webook/templates/arrangement/vue/select2.html
Implements a new Select Room component, leveraging Select2 to get rid of an extra dialog. This component supports room presets.
Additionally also includes a Select2 wrapper component that can be used in other use-cases.
> Add rooms dialog vue

- webook/templates/arrangement/planner/planner_calendar_v2.html
- webook/templates/arrangement/vue/filter/advanced-tree-filter.html
- webook/templates/arrangement/vue/popover_component.html
Implement the "advanced tree filter" component in Vue, and add them to planner_calendar_v2. Not connected to any filtering logic as of yet, but it is ready for it.
> Implement tree filter component (Vue)

- config/settings/base.py
- webook/static/css/base.css
- webook/static/css/project.css
- webook/static/js/advancedTreeFilter.js
- webook/static/modules/planner/commonLib.js
- webook/static/modules/planner/dialog_manager/dialogManager.js
- webook/static/modules/planner/plannerCalendar.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/arrangementInfoDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/inspectEventDialog.html
- webook/templates/base.html
- webook/templates/common/list_view.html
- webook/templates/users/user_detail.html
Merge the new things added to production (missing stuff from earlier staging version, and remove DEFAULT_STORAGE setting). Not the way it usually goes.
> Merge new things on production to staging

- config/settings/base.py
- requirements/base.txt
- requirements/local.txt
- webook/arrangement/forms/file_forms.py
- webook/arrangement/views/mixins/multi_redirect_mixin.py
- webook/users/adapters.py
- webook/utils/meta_utils/meta_mixin.py
Upgrade Django to 4.2 as previous is EOL. 4.2 supported until early 2026.
> Upgrade Django version to 4.2, and solve immediate issues relating to it

- webook/arrangement/api/routers/event_router.py
- webook/arrangement/api/routers/note_router.py
- webook/arrangement/api/routers/room_preset_router.py
- webook/arrangement/api/routers/room_router.py
- webook/arrangement/api/schemas/notes.py
Optimize API list call for remaining relevant entities
> More api list optimization

- config/settings/base.py
- config/urls.py
- locale/nb/LC_MESSAGES/django.po
- webook/utils/manifest_describe.py
A few  improvements to translation and localization, addressing some oddities in nb-no experience.
> Translation and localization improvements

- webook/api/jwt_auth.py
- webook/api/management/commands/register_api_endpoints.py
- webook/api/routers/service_account_router.py
- webook/static/modules/planner/plannerCalendar.js
- Add room presets to sidemenu (missing)
- Fix service account auth
- Fix management command for registering api endpoint
- Fix token decode bug
- Fix auto-scroll behaviour in planner calendar (on initial load, on go-to date)
> Fixes to staging
