- config/settings/base.py
- env.sample.mac_or_linux
- env.sample.windows
- webook/templates/base.html
- webook/utils/context_processors.py
** Summary **
This PR introduces a new "Asset Server" setting, and redone MDB imports on base.html. This is a temporary workaround until we can get MDB into a NPM Proxy internally. As for now it simply gets these assets from another web server, avoiding placing the assets in the repository.
> Add "Asset Server" to the config, and reroute MDB imports through this

- config/settings/base.py
- env.sample.mac_or_linux
- env.sample.windows
- package-lock.json
- package.json
- requirements/base.txt
- webook/templates/base.html
- webook/utils/context_processors.py
**Summary**
This PR installs FullCalendar.
As one might see this is my second go at doing this. Instead of adding the files manually (which FullCalendar discouraged), I have installed django-npm to handle these packages for us (as was encouraged). With the npm static files finder this works like an absolute charm, and I do believe this is an approach we should commit to - and it is especially relevant for issue #28 
To be more concrete I have set up basic config structure around the license key for FullCalendar. You add the license key to your .env, and you're ready to rock and roll. You also need to do npm install, and collectstatic to get the fullcalendar assets.
> Install fullcalendar

- webook/arrangement/models.py
- webook/arrangement/tests/test_models.py
**Summary**
This PR introduces tests for the arrangements models. (arrangements/models.py)
All tests are on the string methods, testing both model.__str__() and str(model).
Coverage of models.py will be 100% after this PR is in.
> Write tests for arrangements models

- webook/arrangement/models.py
This PR makes sure that relationship fields too have their verbose_name parameter set.
These are also translateable.
> Add verbose names to relationship fields

- config/settings/base.py
Closes #59 
This PR changes the default value of FULLCALENDAR_LICENSE_KEY setting to be the trial key.
Reviewer should also double check the licensing terms of FullCalendar to make sure this is in order;
https://fullcalendar.io/docs/premium
https://creativecommons.org/licenses/by-nc-nd/4.0/
> Set FC license key setting default to trial key

- webook/arrangement/urls/planner_urls.py
- webook/arrangement/views/__init__.py
- webook/arrangement/views/planner_views.py
- webook/static/modules/planner/commonLib.js
- webook/static/modules/planner/plannerCalendar.js
- webook/templates/arrangement/planner/planner_calendar.html
- webook/templates/base.html
This PR introduces the arrangement overview calendar, under a new section called planning. (how we organize this isn't really important at this point - we'll deal with that later.)
This calendar shows arrangements as a whole, without including the minute events. This allows for a good top-down view, and an excellent vector from where planning can begin. 
There is a few things I would like some more feedback on, preferably on how we deal with; 
a) Color providers
b) Filtering rules
and c) Resource focuses
I have also taken the liberty of adding a simple popover that displays on-hover of arrangements:
This can be extended further too -- the popover feature allows for quite a lot of interesting possibilities. We just push what HTML we want in, and rock n roll. The way I've set it up means …
> Arrangement calendar

- webook/static/modules/planner/arrangementInspector.js
- webook/static/modules/planner/plannerCalendar.js
- webook/templates/arrangement/arrangement/arrangement_form.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/arrangementInfoDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/newNoteDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/promotePlannerDialog.html
This PR introduces automatic refreshing to the arrangement inspector. The core issue it solves is that for instance after adding a note, the main planner dialog does not refresh to reflect the new note. The previous solution was the "repop" - which just closed and reopened the dialogs, which was too unfriendly. This way each dialog can customize their own "logic" when they are executed, so to speak, as to how it should affect other dialogs, and what needs to be refreshed. Kinda neat.
> Make inspector refreshable

- webook/arrangement/models.py
- webook/templates/arrangement/location/location_detail.html
One of the primary issues with the current archival approach is that there was no way (until now) to cascade the archivals. It makes sense that if you archive a location you also want to archive the rooms contained within that location. This allows for that.
This does demand writing custom logic on each model where cascading archives are needed (or anything else done on archival):
```
class MyLocationModel(models.Model):
def on_archive(self, person_archiving_this):
rooms = self.rooms.all()
for room in rooms:
room.archive(person_archiving_this)
```
I suppose this could be done automatically too. In which case you could just get all the attributes, find the relationships, and go over and archive recursively. Not sure it's necessary at the moment, but it is an interesting prospect.
> Add support for cascading on_archives, and implement for location model

- webook/arrangement/models.py
- webook/arrangement/views/arrangement_views.py
- webook/arrangement/views/planner_views.py
- webook/static/css/project.css
- webook/static/modules/planner/commonLib.js
- webook/static/modules/planner/dialog_manager/dialogManager.js
- webook/static/modules/planner/plannerCalendar.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/arrangementInfoDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/inspectEventDialog.html
- webook/templates/base.html
It is now possible to;
1. Archive arrangements from the planner calendar context menu
2. Archive single events from the planner calendar context menu
3. Archive arrangement from the arrangement inspection dialog
4. Archive event from the event inspection dialog
Still need to add deletion functionality to the timeslot overview in arrangement inspection dialog, but this will come with a rewrite of the backend serie handling and the front-end display of series.
> Add archival functionality to dialogs

- webook/arrangement/models.py
See #169 for more in-depth information about the bug itself.
By inheriting from AutoSlugField I have made a new field type that can access a secondary manager, thus allowing AutoSlugField logic to see archived entities as well. The secondary manager is added via ModelArchiveableMixin.
> Fix archive slug unique constraint violation bug

- webook/arrangement/models.py
- webook/arrangement/urls/event_serie_urls.py
- webook/arrangement/views/__init__.py
- webook/arrangement/views/event_serie_views.py
- webook/static/modules/planner/seriesutil.js
- webook/templates/arrangement/eventserie/preview_calendar.html
- webook/utils/serie_calculator.py
This PR introduces the series calculation algorithm to the server side as an utility that can take a PlanManifest and based on its values generate a serie of simple events.
It is modeled to work and function as the existing implementation in JS does (seriesutil.js).
This is necessary functionality to have on the server-side if one is to do collision analysis on series that have not been generated/saved yet ( we need to calculate them, and not save the events ). It is possible to do this calculation on the clientside and send up the resulting events and then run a collision analysis with this as basis, but this would be a continuation of a bad trend. It is far more future-proof and robust to do this on the server-side. This avoids the issue of Django MAX_POST (in laarge series we will run …
> Implement series calculation algorithm on server side

- config/settings/base.py
- requirements/base.txt
- webook/arrangement/views/planner_views.py
Previously the source of the name/title part of the events shown in the planner calendar view was the arrangement name. It makes more sense that this is the event title.
> Use event name instead of arrangement name as event title in calendar

- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/orderRoomDialog.html
This PR introduces improvements to the room selector, namely:
1. Add a vertical scrollbar to the rooms table, and set a max height. This will avoid the dialog becoming unwieldly long when one has a large amount of locations and rooms defined.
2. Destroy datatables instance before init()
I am not entirely sure about 2, but as we have seen in production instances a datatables error is thrown due to there in some cases already being an instance in the document of the table. This should theoretically make sure that any existing instance is properly destroyed before we try to initialize the table. We need to test and see this actually work in production though, as I am not able to reproduce the bug itself.
> Improve room selector

- webook/static/modules/planner/arrangementCreator.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createSerieDialog.html
Due to a bug in arrangementCreator.js (calling a function before its available) the X button on new timeplan/serie (createSerieDialog) did not show. I have fixed this so that this function is called later on document.ready in the dialog itself, and moved this out of the dialog manager.
> Fix bug where x button would not show when creating new timeplan/serie

- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/dialog_create_event_arrangement.html
On the create simple event dialog the expected visitors input was a text input. This caused, if no value was defined, expected_visitors to be sent up as an empty string. I have alleviated this by changing this input to be of type number, and have a min="0" and default value="0"
> Fix bug where expected_visitors would be sent up as an empty string

- webook/static/modules/planner/dialog_manager/dialogManager.js
One of the major issues reported is an irritating problem where old values are "remembered" into the dialog. There is a feature in most dialogs making it so that when you are editing an arrangement, and creating a new Event or TimePlan, that the recurring values will be copied over into the new Event/TimePlan being created. This prevents a lot of repetitive typing, but also retains the option to be as granular as necessary if the need should arise. The way this is done is through JQUERY selectors fetching the value of the input elements from the other dialogs input elements, and placing this into the corresponding inputs in the form of the other dialog. The dialog manager does not always properly close dialogs after a user has exited them, and they may linger in the document, thus causing …
> Fix "remembering" bug

- .vscode/launch.json
- webook/arrangement/urls/arrangement_urls.py
- webook/arrangement/views/__init__.py
- webook/arrangement/views/arrangement_views.py
- webook/arrangement/views/planner_views.py
- webook/static/modules/planner/arrangementInspector.js
- webook/static/modules/planner/dialog_manager/dialogManager.js
Automatically get and fill in information from arrangement (title, title_en, expected_visitors, display_layouts) when opening new timeplan and new event dialogs on an existing arrangement, as is done in the planning phase.
> Remember arrangement info new timeplan and activity

- webook/static/modules/planner/arrangementCreator.js
Fix a bug on the Arrangement Creator dialog structure, where selected dialogs on the arrangement info would not be auto-filled when one opened the "New Plan/Time Series" dialog.
> Fix bug where display layouts not filled in on new timeseries in planning

- webook/static/modules/planner/plannerCalendar.js
Fix a name / case issue that caused the main planner name to be displayed as "undefined" in popover.
> Fix bug causing main planner name to be undefined in popover

- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/dialog_create_event_arrangement.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/orderRoomDialog.html
This PR introduces yet another redesign of the allocate rooms dialog, but this one should hopefully be permanent. The problem with the previous design was that the search would not be granular enough, and one would not be able to filter down into individual rooms (as each location had its own row, if you then searched for the room in a given location you would get the entire row, which is not ideal when you have 20+ rooms for a location). 
I decided to use tabs, and allow one to switch between locations with this. This also allowed for being able to create unique datatables for each locations room list, which allows for granular search within the respective location. So there is now a vertical tab where they can select between locations, the tab content is the datatable containing the …
> Redesign allocate rooms dialog

- webook/static/modules/planner/commonLib.js
- webook/static/modules/planner/locationCalendar.js
- webook/static/modules/planner/monthNames.js
- webook/static/modules/planner/personCalendar.js
- webook/static/modules/planner/plannerCalendar.js
- webook/templates/arrangement/planner/planner_calendar.html
This PR introduces date navigation functionality in the calendar. This in practice means you can navigate in the calendar via the datepicker utility, which is useful when one needs to go far back or forward in time, in which case the +1/-1 arrow navigation is not optimal.
I also encountered some weird inconsistencies that I resolved with the refreshing logic of the calendars. The location and person calendars did not heed the plannerCalendar.refreshNeeded event, and as thus would not refresh on event creation, ergo not showing new events as they are made. This should be fine now. 
So, for the changelog;
1. Introduced date navigation functionality (made the datepicker up top left in the planner calendar actually do something)
2. Fixed a bug where only the plannercalendar would have events …
> Implement date navigation in planner calendar

- webook/static/modules/planner/locationCalendar.js
- webook/static/modules/planner/monthNames.js
- webook/static/modules/planner/personCalendar.js
- webook/static/modules/planner/plannerCalendar.js
Previously in the calendars we used a hardcoded array to get the month names. This was a naive solution, and JS already has a very good utility for this (date.toLocaleString()) which can give us the month name in the users locale. I have changed the get month logic to use toLocaleString and removed the monthNames.js file which only served the purpose of storing the array.
> Use to localestring to get monthnames

- webook/static/modules/planner/serieConvert.js
Fixes a bug in serieConvert function preventing series with the pattern weekly from being saved. There was an oversight in the serieConvert function where the key would always be manifest.interval. Hence when it arrived in the back-end it would not be read correctly (as back-end looks for "interval"). The manifest prefix is used in some other cases.
> Fix bug preventing weekly pattern from being saved

- webook/static/modules/planner/dialog_manager/dialogManager.js
This PR fixes a bug where if one triggered the dialog render event call in a rapid enough succession two dialogs would be rendered. One flat (not in dialog form), and one "active". This fix makes sure that this can not occur, by making sure that only one rendering function can happen at one time.
> Fix double render bug

- webook/arrangement/views/planner_views.py
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/arrangementInfoDialog.html
This PR introduces a fix to the issue where arrangement file upload would not work. Additionally I have solved the arrangement_list reverse get_success_url problem on all views in PlannerViews. Thought I had fixed these earlier, but it's done now.
The reason I used arrangement_list for get_success_url was primarily naivety. I added it simply to get it to work (as you're supposed to have a success_url to redirect to). This does not really matter on the dialog views where we have zero desire to redirect. To solve this I made JsonFormView. It's a very simple class:
```py
class JsonFormView(FormView):
def form_valid(self, form) -> JsonResponse:
return JsonResponse({ "success": True })
def form_invalid(self, form) -> JsonResponse:
return JsonResponse({ "success": False, "errors": form.errors …
```
> Fix arrangement file upload bug

- webook/static/modules/planner/arrangementInspector.js
- webook/static/modules/planner/querystore.js
This PR introduces a fix to a bug where when editing an existing serie and saving a new serie would be created. This happened due to me forgetting to add the ID of the "source" serie after rewriting the methods responsible for saving events (came in with exclusivity).
> Fix bug where editing serie creates duplicate / new serie

- webook/static/modules/planner/arrangementCreator.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createSerieDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/dialog_create_event_arrangement.html
This PR introduces a fix to a bug where display layouts from CreateArrangementDialog would not be transferred correctly to NewTimePlanDialog.
> Fix a bug where display layouts would be transferred incorrectly across dialogs

- webook/utils/serie_calculator.py
Fix an issue in the weekly strategy for schedule generation where the day would be +1 too many. So if you selected saturday for instance you would get sunday.
> Fix one plus day error

- webook/utils/manifest_describe.py
- webook/utils/serie_calculator.py
This PR introduces a fix for a bug where incorrect day (always tuesday) would be shown in the summary when generated using the server-side version of the summary generator.
> Fix a bug where incorrect day would shown in summary

- webook/static/modules/planner/plannerCalendar.js
Fix main planner name being undefined in event popover
> Fix main planner name undefined bug

- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createSerieDialog.html
Flag/country code was wrong, showed the norwegian one for english title on createSerieDialog form.
> Correct flag/countrycode on english title label on createSerieDialog

- webook/arrangement/forms/event_forms.py
- webook/arrangement/forms/exclusivity_analysis/serie_manifest_form.py
- webook/static/modules/planner/arrangementCreator.js
- webook/static/modules/planner/arrangementInspector.js
- webook/static/modules/planner/commonLib.js
- webook/static/modules/planner/eventInspector.js
- webook/static/modules/planner/querystore.js
- webook/static/modules/planner/serieConvert.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createArrangementDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/dialog_create_event_arrangement.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/inspectEventDialog.html
This PR introduces a permanent solution to the list postings that is not using comma separated strings, and taking use of the Django frameworks functionality in the forms. I am still not entirely sure how I managed to miss this, but miss it I did.
For a simple demo;
```py
class ShoppingTripPlanForm(forms.ModelForm):
shopping_list = forms.ModelMultipleChoiceField(queryset=Article.objects.all(), required=False)
def save(self, commit: bool):
shopping_list = self.cleaned_data["shopping_list"]
```
```js
formData.append("shoppingList", "Apple");
formData.append("shopplingList", "Orange");
```
When Django then receives this it is all good and set up like a QuerySet - which is extremely neat.
I have implemented and tested with this approach for event creation, serie creation, editing existing …
> Fix up list posts once and for all

- webook/static/js/timepickerExtended.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createSerieDialog.html
This PR introduces automatic splitting of the timepickers input (which is a text input), so that when one has 4 characters and all of those are digits, we add a colon in between. 
So say you enter 1500, this would then be converted to 15:00 automatically.
> Implement automatic colon splitting on extended timepicker

- webook/arrangement/models.py
- webook/users/models.py
This PR introduces a fix for the ArchiveIrrespectiveAutoSlugField. This field did not work properly and would always default back to the default manager, thus not solving what it was meant for. The core issue is that model always was none, so we would always just go back to defaults. This must have been an oversight on my part, or alternatively maybe I intended to define the model as a parameter when defining the slug fields on the models. At any rate, this is a screw up on my part, and shouldn't have come into production.
I was originally thinking to just do this;
```py
class ArchiveIrrespectiveAutoSlugField(AutoSlugField):
"""
A subclassed AutoSlugField that can see both archived and non archived entities, thus
preventing slug collisions with entities that are archived.
Use in tandem …
```
> Fix bug where unique slug constraint would be violated if archived entity had the given slug

- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createArrangementDialog.html
This PR introduces a fix to a bug where the english title would be obligatory if a display layout was selected. Previously this was desired behaviour, but this is no longer desired.
> Fix bug where en title would be obligatory if display layout was selected

- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createArrangementDialog.html
This PR introduces a fix to a bug where on the planner (create arrangement) dialog deleted events and series would reappear. The dialog wrote these events and series into its own internal map after receiving it from the dialog manager, thus removing from this map would not remove from the dialog managers context version of the event and series maps, thus when adding a new event these would reappear as it got the context version back (where the delete was not applied). I have made it so that the dialog operates on the contexts version of the maps.
> Fix bug where deleted events are not removed from dialog context thus reappearing

- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/orderRoomDialog.html
Fix a bug where rooms not in view in the table in the room selector would not be included when finishing selection (DataTables would remove the checkbox elements on search, or pagination, when not visible, so that the checkboxes could not be picked up on).
> Fix room selector bug

- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/orderPersonDialog.html
This PR introduces a minor refactor of the order person dialog (in tandem with the bugfix on order room dialog). In practice I have refactored the dialog to use a map to store the selected/checked values, so that selected values can be persisted should the checkbox elements be removed. This is not currently a possibility on the person select dialog, but in the future it will be rewritten to include searching, and probably departments (depending on how we do resources), at which point this would have to be done anyway.
> Use map to store ids in person selector

- webook/static/modules/planner/serieConvert.js
- webook/static/modules/planner/seriesutil.js
- webook/utils/serie_calculator.py
This PR introduces a few fixes to a few various bugs in the serie calculator.
1. Fixed a bug where selecting Sunday in the every day of week pattern would result in an infinite loop. Selecting sunday should now work. This was due to day indexing being wrong, if I remember correctly.
2. Fixed a bug where "weekly" could end up skipping a week if you selected sunday. This happened because we would always +1 (so if cursor was on sunday == week skipped). The +1 thing addresses a very specific concern in the every weekday strategy, and has been isolated to only be run when that strategy is used. (weekday strategy does not move the date_cursor, so we need to move it +1). I'm not particularly happy with the current fix - but it works. Ideally strategy specific logic should be contained within the …
> Fix various bugs in schedule/serie calculator

- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/roomFilterDialog.html
Add scrollbar on room filter dialog, so it doesn't end up extremely unwieldy and long should the amount of rooms registered on the location be great.
> Add scrollbar on room filter dialog

- webook/static/modules/planner/dialog_manager/dialogManager.js
- webook/static/modules/planner/plannerCalendar.js
- webook/templates/common/dialog_list_view.html
Status types are badge-like in popovers. These badges should have the background color which corresponds to the color picked for the statustype. I was not able to get this done initially, and let it be as it was (white background). Style attributes were not respected due to them not being in the popover whitelist/allowlist. I have fixed this, and added this as an allowed attribute in this specific instance.
> fix statustype coloring in popovers (add bg color to status badges)

- webook/static/css/nasj_style.css
- webook/static/modules/planner/dialog_manager/dialogManager.js
- webook/static/modules/planner/dialog_manager/presetSelectManagerPlugin.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/orderRoomDialog.html
Introduces a few adjustments on the room dialog to alleviate some of the pains with it.
1. Locations tabs will now appear on top of the tables (thus freeing up some horizontal real-estate for the table), which will probably/hopefully help in avoiding locations overflowing into rooms table.
2. Made a few alterations and patches to fix state management of the order room dialog. Datatables removes elements from the document when they are not in view -- but the code was assuming these to exist. I have made a few tactical adjustments to make sure that this does not affect us. We now alternatively keep a track of state internally in the dialog plugin, and when any of the datatables are being drawn (which will also be triggered by paginate) we try to check all the checkboxes we know of …
> Adjustments again on room dialog

- webook/arrangement/views/event_views.py
- webook/arrangement/views/planner_views.py
- webook/static/modules/planner/arrangementCreator.js
- webook/static/modules/planner/arrangementInspector.js
- webook/static/modules/planner/broadcast.js
- webook/static/modules/planner/dialog_manager/dialog.js
- webook/static/modules/planner/form_populating_routines.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createSerieDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/dialog_create_event_arrangement.html
- webook/templates/base.html
This PR introduces fixes and a new way of communicating between dialogs, primarily intended to fix the issue of not being able to remember selected rooms and people when editing an existing serie. This proved to be a rather more intricate problem than initially thought, as race conditions were present when sending messages between dialogs through the old way.
The way I solved this is to add a simple message handler class, that is global in scope, and should thus always be present to receive messages. If a dialog is created after messages to it has been sent, then it will be able to find these before-itself messages in window.MessagesFacility, and dialogs will also hook themselves up to MessagesFacility, allowing directly sending messages to MessagesFacility and triggering WHEN events. …
> Communication between dialogs

- webook/arrangement/views/planner_views.py
- webook/static/js/advancedTreeFilter.js
- webook/static/modules/planner/commonLib.js
- webook/static/modules/planner/dialog_manager/dialog.js
- webook/templates/arrangement/planner/planner_calendar.html
This PR contains some improvements and cleanups of the existing filter code, as well as implementing functionality for reflecting the state of a filter unto its triggering element. This is necessary due to the tree-filters being hidden in the dropdowns, thus one can not easily tell the filter state when not actively actually filtering. Now these buttons/dropdown triggerers will have special styling as well as a badge with a total-filtered count, which makes the state a lot better communicated.
> Add better indication of filter status

- webook/arrangement/models.py
- webook/arrangement/urls/status_type_urls.py
- webook/arrangement/views/__init__.py
- webook/arrangement/views/event_views.py
- webook/arrangement/views/generic_views/jstree_list_view.py
- webook/arrangement/views/planner_views.py
- webook/arrangement/views/status_type_views.py
- webook/static/css/base.css
- webook/static/js/components.js
- webook/static/js/jsTreeSelect.js
- webook/static/modules/planner/arrangementCreator.js
- webook/static/modules/planner/arrangementInspector.js
- webook/static/modules/planner/broadcast.js
- webook/static/modules/planner/commonLib.js
- webook/static/modules/planner/dialog_manager/dialogManager.js
- webook/static/modules/planner/dialog_manager/presetSelectManagerPlugin.js
- webook/static/modules/planner/eventInspector.js
- webook/static/modules/planner/form_populating_routines.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/arrangementInfoDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createArrangementDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createSerieDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/dialog_create_event_arrangement.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/inspectEventDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/orderPersonDialog.html
- webook/utils/utc_to_current.py
There has been a particular nasty bug with the selects in-dialog, that has caused a lot of headache. The issue is that the dropdown part of the dropdown menu is rendered way down, and not where it should be, when its container is the parent dialog. If one uses body as the parent of the dropdown then searching in dropdown will not work (though placement will be correct). Interestingly this does not seem to be an issue on Firefox, but is one on Chrome, which is not good. It is either caused by a bug in mdbootstrap or perhaps there is some nuance I am not aware of that affects transform and what not in this very specific context. Hard to say.
Instead of figuring out what it was, as it would be quite time consuming, I elected to do a larger rewrite of the flow. There are already components …
> Fix selects bug -- through rewiring the flow

- webook/static/js/jsTreeSelect.js
This PR introduces a fix to a race condition bug in the JSTREE select utility / component. 
Normally in a JsTree utility we might be attempting to set the value before the tree itself is even initialized. In these cases we "stage" the values on the instance, which will be then set when the JsTree is done initializing. However in some cases this would fail. The core issue was that in the set/stage function there was the possible scenario of the JsTree being initialized, but the JsTree source JSON content not having loaded (thus the tree was not popualted). This messed up, and caused undefined to be set, as there was no node in the tree by the respective id (yet!).  I have altered the behaviour to be such that if the tree exists, but get_node returns false, then the value should be staged, …
> Fix jstree staging malfunction

- webook/arrangement/models.py
- webook/static/modules/planner/arrangementInspector.js
- webook/static/modules/planner/dialog_manager/dialogManager.js
- webook/static/modules/planner/eventInspector.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/arrangementInfoDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/inspectEventDialog.html
This PR introduces changes to the dialog refresh behaviour. Instead of re-initializing the dialog the inner html of the dialog is replaced in-place, thus yielding a smoother user experience. Also added specific handling to re-navigate to the users active tabs on inspect event/inspect arrangement dialogs -- but it remains to be seen if this is good enough,
> Adjustments to dialog behaviour and refresh

- webook/arrangement/facilities/service_ordering.py
- webook/arrangement/views/event_views.py
Automatically cancel a service order if all the events/provisions it is concerned with are deleted/archived.
> Automatically cancel service order if all events are archived

- webook/arrangement/views/event_views.py
- webook/templates/base.html
Cloak the notification bell vue app to avoid visible code before
Additionally run refreshNotifications once before the refresh timer to avoid waiting before first get
> Cloak notification bell render

- webook/arrangement/urls/location_urls.py
- webook/arrangement/views/__init__.py
- webook/arrangement/views/calendar_views.py
- webook/arrangement/views/location_views.py
- webook/arrangement/views/room_views.py
- webook/templates/arrangement/location/location_detail.html
- webook/templates/arrangement/room/partials/_location_room_list.html
- webook/templates/arrangement/room/room_form.html
- webook/templates/arrangement/service/service_detail.html
- webook/templates/arrangement/vue/table_component.html
Rewritten the table tab to use the new vue table component designed for the service stuff. Works well - and does a lot for free. Additionally done some QOL improvements such as adding toasts post actions, and sweetalert for deletion of a room. Editing a room is still its own page, though it may be worth considering using the modal for this purpose - work involved should be minimal to achieve this.
> refactor location rooms table to use vue tablecomponent

- webook/static/modules/planner/dialog_manager/dialog.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createSerieDialog.html
Fix some intermittent errors affecting the loading of the "ORder service" dialog, and create serie dialog.
Fix a race condition causing messages to be picked up by the earlier dead dialogs listener, added a check to make sure that the dialog is still "alive", otherwise the message will be put on queue/wait for the new correct dialog listener to come pick it up.
> Fix intermittent errors on loading order service dialog

- webook/arrangement/models.py
- webook/arrangement/urls/person_urls.py
- webook/arrangement/views/__init__.py
- webook/arrangement/views/generic_views/search_view.py
- webook/arrangement/views/person_views.py
- webook/static/js/popover.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createArrangementDialog.html
Refactor the set main planner mechanism. The current dialog approach is heavy, and has some pesky bugs that it is not worth the time to get to the bottom of. Better to rewrite it leveraging Vue and Popovers to end up at what is, I think, a better result all together. Many flies, one PR.
> Refactor set planner popover

- webook/arrangement/forms/event_forms.py
- webook/arrangement/forms/planner/planner_create_arrangement_form.py
- webook/static/modules/planner/arrangementCreator.js
- webook/static/modules/planner/form_populating_routines.js
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/createArrangementDialog.html
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/dialog_create_event_arrangement.html
- webook/templates/arrangement/vue/js_tree_select_component.html
- webook/templates/arrangement/vue/popover_component.html
This PR introduces a rewrite of the create activity dialog to vue. 
To make things work properly I have written two new components that I have taken in use for both Create Arrangement dialog and Create Activity dialog; Popover and JSTreeSelect. The latter was implemented in vanilla js, and used that way earlier, but now there is a Vue version. 
Using Vue I have also been able to simplify the way Create Arrangement -> Create Activity population works.
> Rewrite create activity dialog to vue

- webook/arrangement/management/commands/refresh_buffers.py
- webook/arrangement/models.py
Fix relevant attributes not being sent on the rigging event from the parent event. Lacking arrangement_type, status, responsible, etc.. would cause these rigging events to not  be shown on filtering, when it is wanted for them to appear along with the parent event.
I refactored the appropriate refresh_buffers method on Event model, and additionally added a new command that can be used to refresh buffers for all events  in the application, so that we can retroactively patch the rigging events with the desired state.
> Fix set attributes on rigging events

- webook/static/modules/planner/calendar_utilities/header_generator.js
Fix month being off by one in the header when using dayview in planner calendar
> Fix month off by one in dayview calendar header

- webook/static/css/nasj_style.css
- webook/static/modules/planner/commonLib.js
- webook/static/modules/planner/locationCalendar.js
- webook/static/modules/planner/personCalendar.js
- webook/static/modules/planner/plannerCalendar.js
Adjust how dates are shown in the cells on the month (dayGridMonth) view. Days will now be on the left of the cell, as opposed to the default right. The day number is encased by a background color. Added in some other design adjustments on the calendar as well.
Additionally revised how navigating via the FC navLinks works. Earlier you could "escape" the external buttons, and enter views not supported. Now when views are changed via navLinks the state will be reflected on the buttons, giving a more fluent and less disjointed experience. Additionally when going to view a specific day via navLink the user will be redirected to timeGridDay (fullcalendar wants to do dayGridDay) which is the only view for day we want to use.
Additionally I have deactivated navLinks on the location calendar and …
> Adjust calendar month view date display

- requirements/base.txt
- webook/api/crud_router.py
- webook/api/jwt_auth.py
- webook/api/paginate.py
- webook/arrangement/api/routers/audience_router.py
- webook/arrangement/api/routers/event_serie_router.py
- webook/onlinebooking/api/city_segment_router.py
- webook/onlinebooking/api/county_router.py
- webook/onlinebooking/api/school_router.py
- Optimize school booking endpoint list gets (prefetch, and select_related in appropriate places)
- Remove async stuff, not possible to run async endpoints with atomic requests enabled. Unable to turn off atomic requests per endpoint with `@decorate_view` and `transaction.non_atomic`. Requires more study. Disabling atomicity project-wide is likely not an acceptable solution.
> Optimize school booking associated endpoints

- webook/api/crud_router.py
- webook/arrangement/api/routers/event_serie_router.py
- webook/arrangement/views/event_views.py
- webook/arrangement/views/planner_views.py
- webook/templates/arrangement/planner/dialogs/arrangement_dialogs/arrangementInfoDialog.html
- webook/templates/arrangement/planner/planner_calendar.html
Completes the rewrite of timeslots tab on arrangement dialog. Uses the API, and event_serie router list endpoint (CrudRouter inherited) to lazily load events and event serie information (as well as files, and serie->events).
On large arrangements the rendering time of seriously large arrangements were untenable, so this should address that particular pain point.
> Complete rewrite of timeslots tab on arrangement dialog, rewrite to lazy loading

- config/settings/base.py
- webook/arrangement/models.py
Reactivate ModelAuditableMixin functionality, add crum middleware back in.
Will allow for tracking who created, and who last updated, on models with the ModelAuditableMixin.
> Reactivate model auditable functionality
